### ISSUE TITLE
Explore opportunities for improving server reliability as we scale hubs.mozilla.com 

### ISSUE THREAD

**Issue by misslivirose** [mozilla/reticulum#469]
- [x] Investigate and optimize top SQL queries #473 
- [x] Investigate and fix most frequent Sentry errors #475 
- [x]  Investigate load on reticulum and repeated connection attempts on unavailable rooms https://github.com/MozillaReality/hubs-discord-bot/issues/115

**Comment by brianpeiris** [comment]
I'm sure we'll have more performance and reliability issues to fix, but I'm going to close this particular issue, since it seems we resolved all the issues in that list.
